[package]
name = "examples-sdsl-rs"
version = "0.1.0"
authors = ["rndhouse <rndhouse@protonmail.com>"]
edition = "2018"

[dependencies]
sdsl = "0.3.1"
anyhow = "1.0.40"
tempdir = "0.3.7"

[build-dependencies]
sdsl = "0.3.1"