[package]
name = "examples-sdsl-rs"
version = "0.1.0"
authors = ["rndhouse <rndhouse@protonmail.com>"]
edition = "2018"

[dependencies]
sdsl-rs = { path = "../sdsl-rs", version = "0.1.0" }
anyhow = "1.0.40"

[build-dependencies]
sdsl-rs = { path = "../sdsl-rs", version = "0.1.0" }